declare module 'grapesjs-tabs'
declare module 'grapesjs-navbar'
declare module 'grapesjs-component-countdown'
declare module 'grapesjs-style-bg'
declare module 'grapesjs-custom-code'
declare module 'grapesjs-plugin-forms'
declare module 'grapesjs-preset-webpage'
declare module 'grapesjs-blocks-basic'
