/**
 * Master Admin - Tenant Configuration Management
 * 
 * Functions for Master Admin to configure OAuth, AI, and automation settings per tenant
 */

import { supabase } from '@/lib/supabase'

// ============================================================================
// Types
// ============================================================================

export interface OAuthConfig {
  google?: {
    enabled: boolean
    clientId: string
    clientSecret: string
    scopes: string[]
    serviceAccountEmail?: string
  }
  microsoft?: {
    enabled: boolean
    clientId: string
    clientSecret: string
    tenantId: string
    scopes: string[]
  }
}

export interface AIConfig {
  provider: 'openai' | 'self-hosted'
  apiKey: string
  model: string
  visionModel: string
  maxTokens: number
  temperature: number
  monthlyBudget: number
  currentSpend: number
  businessTone: {
    style: 'professional' | 'casual' | 'luxury' | 'technical' | 'friendly' | 'edgy'
    vibe: string
    targetAudience: string
    keywords: string[]
  }
}

export interface AutomationConfig {
  ocr: {
    enabled: boolean
    autoCreateSuppliers: boolean
    confidenceThreshold: number
  }
  payments: {
    enabled: boolean
    autoProcess: boolean
    maxRetries: number
    requireApprovalAbove: number
  }
  productGeneration: {
    enabled: boolean
    autoGenerateDescriptions: boolean
    autoFindImages: boolean
    markupPercentage: number
  }
}

export type PackageTier = 'basic' | 'pro' | 'enterprise' | 'custom'

export interface PackageFeatures {
  oauth: {
    google: boolean
    microsoft: boolean
  }
  ai: {
    enabled: boolean
    productGeneration: boolean
    imageAnalysis: boolean
    monthlyTokens: number
  }
  automation: {
    ocrScanning: boolean
    autoPayments: boolean
    supplierManagement: boolean
  }
  features: {
    barcode: boolean
    calendar: boolean
    analytics: boolean
    multiCurrency: boolean
  }
}

export interface PackageLimits {
  products: number // -1 = unlimited
  orders: number
  storage: number // bytes
  users: number
  apiCalls: number
}

export interface TenantConfig {
  id: string
  name: string
  slug: string
  package: PackageTier
  package_features: PackageFeatures
  package_limits: PackageLimits
  oauth_config: OAuthConfig
  ai_config: AIConfig
  automation_config: AutomationConfig
}

// ============================================================================
// Functions
// ============================================================================

/**
 * Get tenant configuration (Master Admin only)
 */
export async function getTenantConfig(tenantId: string): Promise<TenantConfig | null> {
  const { data, error } = await supabase
    .from('tenants')
    .select('id, name, slug, package, package_features, package_limits, oauth_config, ai_config, automation_config')
    .eq('id', tenantId)
    .single()

  if (error) {
    console.error('Failed to get tenant config:', error)
    return null
  }

  return data as TenantConfig
}

/**
 * Check if tenant has access to a feature
 */
export async function tenantHasFeature(
  tenantId: string,
  featurePath: string
): Promise<boolean> {
  const { data, error } = await supabase
    .rpc('tenant_has_feature', {
      p_tenant_id: tenantId,
      p_feature_path: featurePath
    })

  if (error) {
    console.error('Failed to check feature access:', error)
    return false
  }

  return data as boolean
}

/**
 * Update tenant package
 */
export async function updateTenantPackage(
  tenantId: string,
  packageTier: PackageTier
): Promise<{ success: boolean; error?: string }> {
  // Get package template
  const { data: template, error: templateError } = await supabase
    .from('package_templates')
    .select('features, limits')
    .eq('name', packageTier)
    .eq('is_active', true)
    .single()

  if (templateError || !template) {
    return { success: false, error: 'Package template not found' }
  }

  // Update tenant
  const { error } = await supabase
    .from('tenants')
    .update({
      package: packageTier,
      package_features: template.features,
      package_limits: template.limits,
      updated_at: new Date().toISOString()
    })
    .eq('id', tenantId)

  if (error) {
    return { success: false, error: error.message }
  }

  return { success: true }
}

/**
 * Update OAuth configuration for a tenant
 */
export async function updateOAuthConfig(
  tenantId: string,
  oauthConfig: OAuthConfig
): Promise<{ success: boolean; error?: string }> {
  const { error } = await supabase
    .from('tenants')
    .update({ oauth_config: oauthConfig, updated_at: new Date().toISOString() })
    .eq('id', tenantId)

  if (error) {
    return { success: false, error: error.message }
  }

  return { success: true }
}

/**
 * Update AI configuration for a tenant
 */
export async function updateAIConfig(
  tenantId: string,
  aiConfig: AIConfig
): Promise<{ success: boolean; error?: string }> {
  const { error } = await supabase
    .from('tenants')
    .update({ ai_config: aiConfig, updated_at: new Date().toISOString() })
    .eq('id', tenantId)

  if (error) {
    return { success: false, error: error.message }
  }

  return { success: true }
}

/**
 * Update automation configuration for a tenant
 */
export async function updateAutomationConfig(
  tenantId: string,
  automationConfig: AutomationConfig
): Promise<{ success: boolean; error?: string }> {
  const { error } = await supabase
    .from('tenants')
    .update({ automation_config: automationConfig, updated_at: new Date().toISOString() })
    .eq('id', tenantId)

  if (error) {
    return { success: false, error: error.message }
  }

  return { success: true }
}

/**
 * Get AI config for a tenant (used by AI services)
 */
export async function getAIConfigForTenant(tenantId: string): Promise<AIConfig | null> {
  const { data, error } = await supabase
    .from('tenants')
    .select('ai_config')
    .eq('id', tenantId)
    .single()

  if (error || !data) {
    console.error('Failed to get AI config:', error)
    return null
  }

  return data.ai_config as AIConfig
}

/**
 * Get OAuth config for a tenant (used by OAuth services)
 */
export async function getOAuthConfigForTenant(tenantId: string): Promise<OAuthConfig | null> {
  const { data, error } = await supabase
    .from('tenants')
    .select('oauth_config')
    .eq('id', tenantId)
    .single()

  if (error || !data) {
    console.error('Failed to get OAuth config:', error)
    return null
  }

  return data.oauth_config as OAuthConfig
}

