'use client'

import { useState } from 'react'

interface AutomationTabProps {
  config: any
  features: any
  onChange: (config: any) => void
}

export default function AutomationTab({ config, features, onChange }: AutomationTabProps) {
  const [automationConfig, setAutomationConfig] = useState(config || {
    ocr: {
      enabled: true,
      autoCreateSuppliers: true,
      confidenceThreshold: 0.7,
      autoLinkInvoices: true
    },
    payments: {
      enabled: false,
      autoProcess: false,
      maxRetries: 3,
      retryDelayHours: 24,
      approvalThreshold: 10000
    },
    products: {
      enabled: true,
      autoGenerateDescriptions: true,
      autoFindImages: false,
      autoPublish: false,
      defaultMarkup: 30
    }
  })

  const handleChange = (section: string, updates: any) => {
    const newConfig = {
      ...automationConfig,
      [section]: { ...automationConfig[section], ...updates }
    }
    setAutomationConfig(newConfig)
    onChange(newConfig)
  }

  return (
    <div className="space-y-8">
      {/* OCR Automation */}
      <div className="border rounded-lg p-6">
        <div className="flex items-center justify-between mb-4">
          <div>
            <h3 className="text-lg font-bold text-gray-900">OCR Invoice Scanning</h3>
            <p className="text-sm text-gray-600">Automatically scan and process supplier invoices</p>
          </div>
          <label className="flex items-center cursor-pointer">
            <input
              type="checkbox"
              checked={automationConfig.ocr.enabled}
              onChange={(e) => handleChange('ocr', { enabled: e.target.checked })}
              disabled={!features?.automation?.ocrScanning}
              className="w-5 h-5 text-blue-600 rounded focus:ring-blue-500"
            />
            <span className="ml-2 text-sm font-medium text-gray-700">
              {automationConfig.ocr.enabled ? 'Enabled' : 'Disabled'}
            </span>
          </label>
        </div>

        {!features?.automation?.ocrScanning && (
          <div className="bg-yellow-50 border border-yellow-200 rounded p-3 mb-4">
            <p className="text-sm text-yellow-800">
              ⚠️ OCR scanning is not available in the current package.
            </p>
          </div>
        )}

        {automationConfig.ocr.enabled && (
          <div className="space-y-4">
            <label className="flex items-center">
              <input
                type="checkbox"
                checked={automationConfig.ocr.autoCreateSuppliers}
                onChange={(e) => handleChange('ocr', { autoCreateSuppliers: e.target.checked })}
                className="w-4 h-4 text-blue-600 rounded focus:ring-blue-500"
              />
              <span className="ml-2 text-sm text-gray-700">
                Auto-create suppliers from invoices
              </span>
            </label>

            <label className="flex items-center">
              <input
                type="checkbox"
                checked={automationConfig.ocr.autoLinkInvoices}
                onChange={(e) => handleChange('ocr', { autoLinkInvoices: e.target.checked })}
                className="w-4 h-4 text-blue-600 rounded focus:ring-blue-500"
              />
              <span className="ml-2 text-sm text-gray-700">
                Auto-link invoices to suppliers
              </span>
            </label>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Confidence Threshold ({(automationConfig.ocr.confidenceThreshold * 100).toFixed(0)}%)
              </label>
              <input
                type="range"
                min="0.5"
                max="1"
                step="0.05"
                value={automationConfig.ocr.confidenceThreshold}
                onChange={(e) => handleChange('ocr', { confidenceThreshold: parseFloat(e.target.value) })}
                className="w-full"
              />
              <p className="text-xs text-gray-500 mt-1">
                Minimum confidence level for OCR data extraction
              </p>
            </div>
          </div>
        )}
      </div>

      {/* Payment Automation */}
      <div className="border rounded-lg p-6">
        <div className="flex items-center justify-between mb-4">
          <div>
            <h3 className="text-lg font-bold text-gray-900">Autonomous Payment Processing</h3>
            <p className="text-sm text-gray-600">Automatically process supplier payments</p>
          </div>
          <label className="flex items-center cursor-pointer">
            <input
              type="checkbox"
              checked={automationConfig.payments.enabled}
              onChange={(e) => handleChange('payments', { enabled: e.target.checked })}
              disabled={!features?.automation?.autoPayments}
              className="w-5 h-5 text-blue-600 rounded focus:ring-blue-500"
            />
            <span className="ml-2 text-sm font-medium text-gray-700">
              {automationConfig.payments.enabled ? 'Enabled' : 'Disabled'}
            </span>
          </label>
        </div>

        {!features?.automation?.autoPayments && (
          <div className="bg-yellow-50 border border-yellow-200 rounded p-3 mb-4">
            <p className="text-sm text-yellow-800">
              ⚠️ Auto payments are not available in the current package. Upgrade to Pro or Enterprise.
            </p>
          </div>
        )}

        {automationConfig.payments.enabled && (
          <div className="space-y-4">
            <label className="flex items-center">
              <input
                type="checkbox"
                checked={automationConfig.payments.autoProcess}
                onChange={(e) => handleChange('payments', { autoProcess: e.target.checked })}
                className="w-4 h-4 text-blue-600 rounded focus:ring-blue-500"
              />
              <span className="ml-2 text-sm text-gray-700">
                Auto-process payments on due date
              </span>
            </label>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Approval Threshold (ZAR)
              </label>
              <input
                type="number"
                value={automationConfig.payments.approvalThreshold}
                onChange={(e) => handleChange('payments', { approvalThreshold: parseInt(e.target.value) })}
                className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-blue-500 focus:border-blue-500"
              />
              <p className="text-xs text-gray-500 mt-1">
                Payments above this amount require manual approval
              </p>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Max Retry Attempts
              </label>
              <input
                type="number"
                min="1"
                max="5"
                value={automationConfig.payments.maxRetries}
                onChange={(e) => handleChange('payments', { maxRetries: parseInt(e.target.value) })}
                className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-blue-500 focus:border-blue-500"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Retry Delay (hours)
              </label>
              <input
                type="number"
                min="1"
                max="72"
                value={automationConfig.payments.retryDelayHours}
                onChange={(e) => handleChange('payments', { retryDelayHours: parseInt(e.target.value) })}
                className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-blue-500 focus:border-blue-500"
              />
            </div>
          </div>
        )}
      </div>

      {/* Product Automation */}
      <div className="border rounded-lg p-6">
        <div className="flex items-center justify-between mb-4">
          <div>
            <h3 className="text-lg font-bold text-gray-900">Product Generation</h3>
            <p className="text-sm text-gray-600">AI-powered product creation from supplier pricelists</p>
          </div>
          <label className="flex items-center cursor-pointer">
            <input
              type="checkbox"
              checked={automationConfig.products.enabled}
              onChange={(e) => handleChange('products', { enabled: e.target.checked })}
              disabled={!features?.automation?.supplierManagement}
              className="w-5 h-5 text-blue-600 rounded focus:ring-blue-500"
            />
            <span className="ml-2 text-sm font-medium text-gray-700">
              {automationConfig.products.enabled ? 'Enabled' : 'Disabled'}
            </span>
          </label>
        </div>

        {automationConfig.products.enabled && (
          <div className="space-y-4">
            <label className="flex items-center">
              <input
                type="checkbox"
                checked={automationConfig.products.autoGenerateDescriptions}
                onChange={(e) => handleChange('products', { autoGenerateDescriptions: e.target.checked })}
                disabled={!features?.ai?.productGeneration}
                className="w-4 h-4 text-blue-600 rounded focus:ring-blue-500"
              />
              <span className="ml-2 text-sm text-gray-700">
                Auto-generate product descriptions with AI
              </span>
            </label>

            <label className="flex items-center">
              <input
                type="checkbox"
                checked={automationConfig.products.autoFindImages}
                onChange={(e) => handleChange('products', { autoFindImages: e.target.checked })}
                disabled={!features?.ai?.imageAnalysis}
                className="w-4 h-4 text-blue-600 rounded focus:ring-blue-500"
              />
              <span className="ml-2 text-sm text-gray-700">
                Auto-find product images with AI Vision
              </span>
            </label>

            <label className="flex items-center">
              <input
                type="checkbox"
                checked={automationConfig.products.autoPublish}
                onChange={(e) => handleChange('products', { autoPublish: e.target.checked })}
                className="w-4 h-4 text-blue-600 rounded focus:ring-blue-500"
              />
              <span className="ml-2 text-sm text-gray-700">
                Auto-publish products (skip review)
              </span>
            </label>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Default Markup (%)
              </label>
              <input
                type="number"
                min="0"
                max="200"
                value={automationConfig.products.defaultMarkup}
                onChange={(e) => handleChange('products', { defaultMarkup: parseInt(e.target.value) })}
                className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-blue-500 focus:border-blue-500"
              />
              <p className="text-xs text-gray-500 mt-1">
                Default markup percentage for auto-generated products
              </p>
            </div>
          </div>
        )}
      </div>
    </div>
  )
}

