import { AWAKE_IMAGES } from '../awake-images'
import type { CatalogProductDef } from './types'

/** Single source of truth for Awake SA product catalog (Jul 2026) */
export const CATALOG_DEFINITIONS: CatalogProductDef[] = [
  // ── Complete jetboards ──────────────────────────────────────────────
  {
    id: 'ravik-explore',
    name: 'Awake RÄVIK Explore XR 4',
    category: 'jetboards',
    categoryTag: 'Jetboard',
    euRetailExVat: 9990,
    image: AWAKE_IMAGES.ravik.explore,
    battery: 'XR 4 (65 min)',
    skillLevel: 'Beginner',
    description:
      'Entry-level electric jetboard with impressive performance. Perfect for beginners and families.',
    specs: ['Top Speed: ~55 km/h', 'Battery: XR 4 (~60 min)', '2 Year Warranty'],
    features: ['Beginner friendly', 'Unmatched stability', 'Quick battery swap'],
    whatsIncluded: [
      'RÄVIK Explore Board',
      'Flex Battery XR 4 (65 min)',
      'Flex Hand Controller 4',
      'Flex Battery Charger',
      'Power Key Leash',
      'RÄVIK Board Bag Kit',
    ],
    compareSpecs: {
      topSpeed: '~55 km/h',
      range: '~60 min',
      weight: '32 kg',
      battery: 'XR 4',
      construction: 'Composite',
    },
    legacySlugs: ['ravik-3'],
  },
  {
    id: 'ravik-adventure',
    name: 'Awake RÄVIK Adventure XR 4',
    category: 'jetboards',
    categoryTag: 'Jetboard',
    euRetailExVat: 13990,
    image: AWAKE_IMAGES.ravik.adventure,
    battery: 'XR 4 (65 min)',
    skillLevel: 'Intermediate',
    description:
      'Mid-range performance jetboard. Perfect balance of power and versatility for expedition rides.',
    specs: ['Top Speed: ~55 km/h', 'Battery: XR 4 (~60 min)', '2 Year Warranty'],
    features: ['Elegant & adaptable', 'Enhanced power delivery', 'Adventure-ready'],
    whatsIncluded: [
      'RÄVIK Adventure Board',
      'Flex Battery XR 4 (65 min)',
      'Flex Hand Controller 4',
      'Flex Battery Charger',
      'Power Key Leash',
      'RÄVIK Board Bag Kit',
    ],
    compareSpecs: {
      topSpeed: '~55 km/h',
      range: '~60 min',
      weight: '32 kg',
      battery: 'XR 4',
      construction: 'Composite',
    },
  },
  {
    id: 'ravik-ultimate',
    name: 'Awake RÄVIK Ultimate XR 4',
    category: 'jetboards',
    categoryTag: 'Jetboard',
    euRetailExVat: 15990,
    image: AWAKE_IMAGES.ravik.ultimate,
    battery: 'XR 4 (65 min)',
    skillLevel: 'Expert',
    description:
      'Top-tier performance electric jetboard for experienced riders who demand peak performance.',
    specs: ['Top Speed: ~58 km/h', 'Battery: XR 4 (~60 min)', 'Board weight: 16 kg', '2 Year Warranty'],
    features: ['Fastest & most agile', 'Lightweight carbon build', 'Competition ready'],
    whatsIncluded: [
      'RÄVIK Ultimate Board',
      'Flex Battery XR 4 (65 min)',
      'Flex Hand Controller 4',
      'Flex Battery Charger',
      'Power Key Leash',
      'RÄVIK Board Bag Kit',
    ],
    compareSpecs: {
      topSpeed: '~58 km/h',
      range: '~60 min',
      weight: '16 kg',
      battery: 'XR 4',
      construction: 'Carbon fibre',
    },
    legacySlugs: ['ravik-s'],
  },
  {
    id: 'brabus-shadow-explore',
    name: 'BRABUS x Awake Shadow Explore',
    category: 'jetboards',
    categoryTag: 'Limited Edition',
    euRetailExVat: 15900,
    image: AWAKE_IMAGES.brabus.shadowExplore,
    badge: 'Limited Edition',
    battery: 'XR 4 (65 min)',
    skillLevel: 'Expert',
    description:
      'Exclusive BRABUS collaboration — luxury meets performance. Limited edition worldwide.',
    specs: ['Max Speed: 60 km/h', 'Exclusive BRABUS Design', 'Limited edition'],
    features: ['Numbered edition', 'Signature BRABUS styling', "Collector's item"],
    whatsIncluded: [
      'BRABUS x Awake Shadow Explore Board',
      'BRABUS Battery XR 4 (65 min)',
      'BRABUS Hand Controller 4',
      'Flex Battery Charger',
      'Power Key Leash',
      'RÄVIK Board Bag Kit',
    ],
    compareSpecs: {
      topSpeed: '60 km/h',
      range: '~60 min',
      weight: '36 kg',
      battery: 'BRABUS XR 4',
      construction: 'Carbon fibre',
    },
    legacySlugs: ['brabus-shadow'],
  },

  // ── Complete eFoils ─────────────────────────────────────────────────
  {
    id: 'vinga-carve',
    name: 'Awake VINGA Carve LR 4',
    category: 'efoils',
    categoryTag: 'eFoil',
    euRetailExVat: 11990,
    image: AWAKE_IMAGES.vinga.adventure,
    battery: 'LR 4 (90 min)',
    skillLevel: 'Beginner to Intermediate',
    description:
      'Versatile eFoil for carving and learning. The current-generation VINGA entry model (replaces legacy VINGA 2 naming).',
    specs: ['Battery: LR 4 (90 min)', 'Silent electric propulsion', '2 Year Warranty'],
    features: ['Easy to learn', 'Balanced ride', 'Long-range capable'],
    whatsIncluded: [
      'VINGA Carve Board',
      'Flex Battery LR 4 (90 min)',
      'Flex Hand Controller 4',
      'Flex Battery Charger',
      'Wing kit (model dependent)',
      'VINGA Board Bag Kit',
    ],
    compareSpecs: {
      topSpeed: '~45 km/h',
      range: '90 min',
      weight: '28 kg',
      battery: 'LR 4',
      construction: 'Carbon fibre',
    },
    legacySlugs: ['vinga-2'],
  },
  {
    id: 'vinga-adventure-lr4',
    name: 'Awake VINGA Adventure LR 4',
    category: 'efoils',
    categoryTag: 'eFoil',
    pricingStatus: 'contact',
    image: AWAKE_IMAGES.vinga.adventure,
    battery: 'LR 4 (90 min)',
    skillLevel: 'Beginner to Intermediate',
    description: 'Extended range eFoil for long sessions.',
    specs: ['Battery: LR 4 (90 min)', 'CRUISE 1600 wing included', '2 Year Warranty'],
    features: ['Longest ride time', 'Easy to learn'],
  },
  {
    id: 'vinga-adventure-xr4',
    name: 'Awake VINGA Adventure XR 4',
    category: 'efoils',
    categoryTag: 'eFoil',
    pricingStatus: 'contact',
    image: AWAKE_IMAGES.vinga.adventure,
    battery: 'XR 4 (65 min)',
    skillLevel: 'Intermediate',
    description: 'Performance-focused eFoil with XR battery.',
  },
  {
    id: 'vinga-ultimate-lr4',
    name: 'Awake VINGA Ultimate LR 4',
    category: 'efoils',
    categoryTag: 'eFoil',
    pricingStatus: 'contact',
    image: AWAKE_IMAGES.vinga.ultimate,
    battery: 'LR 4 (90 min)',
    skillLevel: 'Intermediate to Expert',
    description: 'Advanced eFoil with extended ride time.',
  },
  {
    id: 'vinga-ultimate-xr4',
    name: 'Awake VINGA Ultimate XR 4',
    category: 'efoils',
    categoryTag: 'eFoil',
    pricingStatus: 'contact',
    image: AWAKE_IMAGES.vinga.ultimate,
    battery: 'XR 4 (65 min)',
    skillLevel: 'Expert',
    description: 'Top-spec eFoil with ultimate performance.',
  },

  // ── Batteries ───────────────────────────────────────────────────────
  {
    id: 'flex-battery-lr4',
    name: 'Awake Flex Battery LR 4 (90 min)',
    category: 'batteries',
    categoryTag: 'Battery',
    euRetailExVat: 2990,
    image: AWAKE_IMAGES.batteries.flexLR4,
    description: 'Long range eFoil battery — 90 minutes ride time.',
    specs: ['90 min ride time', 'Weight: 12 kg', 'Quick-swap design'],
  },
  {
    id: 'flex-battery-xr4',
    name: 'Awake Flex Battery XR 4',
    category: 'batteries',
    categoryTag: 'Battery',
    euRetailExVat: 4990,
    image: AWAKE_IMAGES.batteries.flexXR4,
    description: 'High-performance jetboard and eFoil battery — ~60 minutes ride time.',
    specs: ['~60 min ride time', 'Weight: 18.5 kg', 'SmartPair Technology'],
  },
  {
    id: 'brabus-battery-xr4',
    name: 'BRABUS Battery XR 4',
    category: 'batteries',
    categoryTag: 'Battery',
    euRetailExVat: 5490,
    image: AWAKE_IMAGES.batteries.brabusXR4,
    badge: 'Limited Edition',
    description: 'Exclusive BRABUS x Awake limited edition battery.',
  },
  {
    id: 'battery-bag',
    name: 'Awake Battery Backpack',
    category: 'batteries',
    categoryTag: 'Battery',
    euRetailExVat: 120,
    image: AWAKE_IMAGES.accessories.batteryBackpack,
    description: 'Dedicated backpack for safe transport of Awake batteries.',
  },
  {
    id: 'battery-charger',
    name: 'Awake Flex Battery Charger',
    category: 'batteries',
    categoryTag: 'Battery',
    euRetailExVat: 1090,
    image: AWAKE_IMAGES.accessories.charger,
    description: 'Fast battery charger for all Awake Flex batteries.',
  },
  {
    id: 'battery-health-report',
    name: 'Battery Health Report',
    category: 'batteries',
    categoryTag: 'Service',
    euRetailExVat: 30,
    image: AWAKE_IMAGES.accessories.charger,
    description: 'Diagnostic service report for your Awake battery (service item, not physical stock).',
  },

  // ── Wing kits ───────────────────────────────────────────────────────
  {
    id: 'powder-1800-wing-kit',
    name: 'POWDER 1800 Wing Kit',
    category: 'wings',
    categoryTag: 'Wing Kit',
    euRetailExVat: 1090,
    image: AWAKE_IMAGES.accessories.powderWing,
    description: 'POWDER 1800 wing kit for versatile eFoil performance.',
  },
  {
    id: 'powder-1400-wing-kit',
    name: 'POWDER 1400 Wing Kit',
    category: 'wings',
    categoryTag: 'Wing Kit',
    euRetailExVat: 1090,
    image: AWAKE_IMAGES.accessories.powderWing,
    description: 'POWDER 1400 wing kit for versatile eFoil performance.',
  },
  {
    id: 'fluid-1300-wing-kit',
    name: 'FLUID 1300 Wing Kit',
    category: 'wings',
    categoryTag: 'Wing Kit',
    euRetailExVat: 1090,
    image: AWAKE_IMAGES.accessories.fluidWing,
    description: 'FLUID 1300 wing kit for high-speed eFoil performance.',
  },
  {
    id: 'fluid-1000-wing-kit',
    name: 'FLUID 1000 Wing Kit',
    category: 'wings',
    categoryTag: 'Wing Kit',
    euRetailExVat: 1090,
    image: AWAKE_IMAGES.accessories.fluidWing,
    description: 'FLUID 1000 wing kit for high-speed eFoil performance.',
  },
  {
    id: 'cruise-1600-wing-kit',
    name: 'CRUISE 1600 Wing Kit',
    category: 'wings',
    categoryTag: 'Wing Kit',
    pricingStatus: 'contact',
    image: AWAKE_IMAGES.accessories.powderWing,
    description: 'CRUISE 1600 wing kit — often bundled with VINGA packages. Contact for standalone pricing.',
  },

  // ── Board gear & accessories ────────────────────────────────────────
  {
    id: 'ravik-fins',
    name: 'RÄVIK Fins',
    category: 'accessories',
    categoryTag: 'Parts',
    euRetailExVat: 200,
    image: AWAKE_IMAGES.accessories.ravikFins,
    description: 'Standard fin set for RÄVIK jetboards (set of 3).',
  },
  {
    id: 'carbon-fins',
    name: 'Awake Carbon Fins',
    category: 'accessories',
    categoryTag: 'Parts',
    euRetailExVat: 290,
    image: AWAKE_IMAGES.accessories.carbonFins,
    description: 'Premium carbon fiber fin set (set of 3).',
  },
  {
    id: 'life-vest',
    name: 'Awake Life Vest',
    category: 'accessories',
    categoryTag: 'Safety',
    euRetailExVat: 290,
    image: AWAKE_IMAGES.accessories.lifeVest,
    description: 'CE certified life vest designed for water sports.',
  },
  {
    id: 'beach-mat',
    name: 'Awake Beach Mat',
    category: 'accessories',
    categoryTag: 'Parts',
    euRetailExVat: 190,
    image: AWAKE_IMAGES.accessories.beachMat,
    description: 'Portable beach mat for protecting your board and gear.',
  },
  {
    id: 'awake-dock',
    name: 'Awake Inflatable Dock',
    category: 'accessories',
    categoryTag: 'Storage',
    euRetailExVat: 3490,
    image: AWAKE_IMAGES.accessories.inflatableDock,
    description: 'Inflatable floating dock for easy water access.',
  },
  {
    id: 'jetboard-tube',
    name: 'Awake Jetboard Tube',
    category: 'accessories',
    categoryTag: 'Parts',
    euRetailExVat: 590,
    image: AWAKE_IMAGES.accessories.jetboardTube,
    description: 'Inflatable tube accessory for towing behind your jetboard.',
  },
  {
    id: 'board-stand',
    name: 'eFoil Board Stand',
    category: 'accessories',
    categoryTag: 'Storage',
    euRetailExVat: 490,
    image: AWAKE_IMAGES.accessories.wallMount,
    description: 'Premium stand for displaying your Awake board.',
  },
  {
    id: 'wall-mount',
    name: 'RÄVIK Wall Mount',
    category: 'accessories',
    categoryTag: 'Storage',
    euRetailExVat: 1090,
    image: AWAKE_IMAGES.accessories.wallMount,
    description: 'Wall mounting system for RÄVIK boards.',
  },

  // ── Contact for pricing (EU retail not yet confirmed) ───────────────
  {
    id: 'flex-hand-controller',
    name: 'Flex Hand Controller',
    category: 'accessories',
    categoryTag: 'Electronics',
    pricingStatus: 'contact',
    image: AWAKE_IMAGES.accessories.handController,
    description: 'Wireless hand controller with precise throttle control.',
  },
  {
    id: 'controller-charger',
    name: 'Induction Charger',
    category: 'accessories',
    categoryTag: 'Electronics',
    pricingStatus: 'contact',
    image: AWAKE_IMAGES.accessories.controllerCharger,
    description: 'Dedicated charger for Awake hand controllers.',
  },
  {
    id: 'board-bag-kit',
    name: 'RÄVIK/VINGA Board Bag Kit',
    category: 'accessories',
    categoryTag: 'Bag',
    pricingStatus: 'contact',
    image: AWAKE_IMAGES.accessories.boardBag,
    description: 'Protective bag kit for RÄVIK jetboards and VINGA eFoils.',
  },
  {
    id: 'premium-travel-bag',
    name: 'Premium Travel Bag',
    category: 'accessories',
    categoryTag: 'Bag',
    pricingStatus: 'contact',
    image: AWAKE_IMAGES.accessories.boardBag,
    description: 'Premium travel bag for complete protection during transport.',
  },
  {
    id: 'power-key-leash',
    name: 'Awake Power Key Leash',
    category: 'accessories',
    categoryTag: 'Parts',
    pricingStatus: 'contact',
    image: AWAKE_IMAGES.accessories.powerKeyLeash,
    description: 'Safety leash for your power key.',
  },
  {
    id: 'competition-power-key',
    name: 'Competition Power Key',
    category: 'accessories',
    categoryTag: 'Parts',
    pricingStatus: 'contact',
    image: AWAKE_IMAGES.accessories.competitionKey,
    description: 'Competition power key for unlocking maximum performance.',
  },
  {
    id: 'foot-straps',
    name: 'Foot Straps',
    category: 'accessories',
    categoryTag: 'Parts',
    pricingStatus: 'contact',
    image: AWAKE_IMAGES.accessories.footStraps,
    description: 'Adjustable foot straps for enhanced control.',
  },
  {
    id: 'tshirt',
    name: 'Awake T-Shirt',
    category: 'apparel',
    categoryTag: 'Apparel',
    pricingStatus: 'contact',
    image: AWAKE_IMAGES.accessories.tshirt,
    description: 'Official Awake branded t-shirt.',
  },
  {
    id: 'cap',
    name: 'Awake Cap',
    category: 'apparel',
    categoryTag: 'Apparel',
    pricingStatus: 'contact',
    image: AWAKE_IMAGES.accessories.cap,
    description: 'Branded Awake cap.',
  },

  // ── Apparel (new line) ──────────────────────────────────────────────
  {
    id: 'wetsuit',
    name: 'Awake Wetsuit',
    category: 'apparel',
    categoryTag: 'Apparel',
    euRetailExVat: 390,
    image: AWAKE_IMAGES.accessories.wetsuit,
    description: 'Full wetsuit designed for water sports. 4/3mm thickness.',
  },
  {
    id: 'neo-jacket',
    name: 'Awake Neo Jacket',
    category: 'apparel',
    categoryTag: 'Apparel',
    euRetailExVat: 190,
    image: AWAKE_IMAGES.accessories.neoJacket,
    description: 'Neoprene jacket for layering in cooler conditions.',
  },
  {
    id: 'ladys-neo-suit',
    name: "Awake Lady's Neo Suit",
    category: 'apparel',
    categoryTag: 'Apparel',
    euRetailExVat: 190,
    image: AWAKE_IMAGES.accessories.ladysNeoSuit,
    description: "Women's neoprene suit designed for comfort and style.",
  },

  // ── Trade / board-only (contact) ────────────────────────────────────
  {
    id: 'ravik-explore-board',
    name: 'RÄVIK Explore (Board Only)',
    category: 'boards',
    categoryTag: 'Board Only',
    pricingStatus: 'contact',
    image: AWAKE_IMAGES.ravik.explore,
    description: 'Board without battery.',
  },
  {
    id: 'ravik-adventure-board',
    name: 'RÄVIK Adventure (Board Only)',
    category: 'boards',
    categoryTag: 'Board Only',
    pricingStatus: 'contact',
    image: AWAKE_IMAGES.ravik.adventure,
    description: 'Board without battery.',
  },
  {
    id: 'ravik-ultimate-board',
    name: 'RÄVIK Ultimate (Board Only)',
    category: 'boards',
    categoryTag: 'Board Only',
    pricingStatus: 'contact',
    image: AWAKE_IMAGES.ravik.ultimate,
    description: 'Board without battery.',
  },
]

/** Products featured on /compare */
export const COMPARE_PRODUCT_IDS = [
  'ravik-explore',
  'ravik-adventure',
  'ravik-ultimate',
  'vinga-carve',
  'brabus-shadow-explore',
] as const
